title: joker's Homepage
page-top-title: joker-cui
top-section-bg-text: Be what you wanna be
home-subtitle: Jiajun Cui &ensp;|&ensp;崔家骏
copyright-text: '&copy; Yourname 2023-2025. All Rights Reserved.'
